1D dilated convolutional layer.
hfp/libxsmm pull request #429
Opened 2020-11-24 18:03 UTC by narendrachaudhary51

This folder contains a PyTorch convolutional layer that can be used to replace the existing PyTorch nn.Conv1d layer. We wrote the optimized convolutional layer code using libxsmm library's brgemm functions. This optimized layer has both float32 and bfloat16 implementations.

2020-11-24 20:45 UTC, alheinecke requested changes
This file has no lic headers, where is the code from?

Why are the LIBXSMM intrinsics and/or TPPs for FP32<->BF16 not used. I suggest using the LIBXSMM TPPs (mateltwise) for this

2020-11-24 20:46 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
This file has no lic headers, where is the code from?

Why are the LIBXSMM intrinsics and/or TPPs for FP32<->BF16 not used. I suggest using the LIBXSMM TPPs (mateltwise) for this

2020-11-24 20:47 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#include<immintrin.h>
Please add lic header

2020-11-24 20:47 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#include<libxsmm_intrinsics_x86.h>
see comment on BF16 intrinsic above

2020-11-24 20:48 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
here we have the mateltwise transform TPP for VNNI formating

2020-11-24 20:48 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +void convert_f32_bf16(float* in, bfloat16* out, int len)
here we also have a mateltwise TPP

2020-11-24 20:49 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
we have a matetlwise kernel for setting 2d arrays to 0

2020-11-24 20:50 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    for(int kw = 0; kw < WW_t; kw++){                               // Loop to permute weight tensor dimensions
Could a transpose TPP used here, is this a common kernel?

2020-11-24 20:51 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for(int filter=0; filter < F_t; filter++){
could we use a mateltwise kernel here? Do we need to add one?

2020-11-24 20:51 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int channel = 0; channel < C_t; channel++){                 /* Loop for initilization of grad array */
we have a mateltwise kernel for setting a matrix to 0

2020-11-24 20:52 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
it's better to use the mateltwise transform kernel

2020-11-24 20:52 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for (int channel=0; channel < C_t; channel++){
can we use a  mateltwise kernel?

2020-11-24 20:53 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_backward_bf16(at::Tensor& grad, at::Tensor& output){
why not using a framework operation here?

2020-11-24 20:54 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_forward_bf16(at::Tensor& input){
why not using a framework operation here?

2020-11-24 20:55 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/build/temp.linux-x86_64-3.6/.ninja_log
> +# ninja log v5
This file should not be part of the PR as it's not source.

2020-11-24 20:55 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/build/temp.linux-x86_64-3.6/build.ninja
> +ninja_required_version = 1.3
This file should not be part of the PR as it's not source.

2020-11-24 20:55 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/conv1dopti_layer.egg-info/PKG-INFO
> +Metadata-Version: 1.0
This file should not be part of the PR as it's not source.

2020-11-24 20:56 UTC, alheinecke requested changes
There are several issues and also binary and log files are part of the PR which should be removed

2020-11-25 04:06 UTC, ddkalamk commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_backward_bf16(at::Tensor& grad, at::Tensor& output){
Pytorch still doesn't support ReLU for BF16... So we need this until they add it

2020-11-25 04:18 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_backward_bf16(at::Tensor& grad, at::Tensor& output){
@egeor I think we can generate a standalone TPP for ReLU in BF16 correct?

2020-11-25 04:20 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_backward_bf16(at::Tensor& grad, at::Tensor& output){
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L179

2020-11-25 04:31 UTC, egeor commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_backward_bf16(at::Tensor& grad, at::Tensor& output){
> @egeor I think we can generate a standalone TPP for ReLU in BF16 correct?

Sure. In fact I have already a TPP for bwd relu, however it reads bitmasks. it can be trivially extended to read bf16 tensor.

2020-11-25 05:36 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
I modified the existing function (replace line 54 by line 55). I needed to do that to handle VNNI reformat for submatrix. I mentioned this to @egeor. He said that we should not make the change in existing function and suggested me to make the changes locally in my code.

2020-11-25 05:41 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
hmm: this code should handle this: https://github.com/hfp/libxsmm/blob/master/samples/eltwise/eltwise_transform.c#L371 or what do you need differently?

2020-11-25 05:58 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
I need to use different values for ld_in and ld_out. I can't use the same value for both. I don't see ld_in and ld_out options on this function.

2020-11-25 06:00 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
https://github.com/hfp/libxsmm/blob/master/samples/eltwise/eltwise_transform.c#L424

2020-11-30 04:07 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/conv1dopti_layer.egg-info/PKG-INFO
> +Metadata-Version: 1.0
Removed this file

2020-11-30 04:07 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/build/temp.linux-x86_64-3.6/build.ninja
> +ninja_required_version = 1.3
Removed this file.

2020-11-30 04:08 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/build/temp.linux-x86_64-3.6/.ninja_log
> +# ninja log v5
Removed this file.

2020-11-30 04:12 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#include<immintrin.h>
Added lic header.

2020-11-30 07:26 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
In the FP32 version of this code. I replace the existing transform kernel with libxsmm_dispatch_meltw_transform() and I am observing 3-4% slowdown. Is this expected? I am taking a lot of small matrix transforms in loop, instead of one large matrix transform.

2020-11-30 08:26 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_forward_bf16(at::Tensor& input){
Same as the forward pass kernel. The PyTorch framework doesn't support ReLU for BF16.

2020-11-30 08:42 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for(int filter=0; filter < F_t; filter++){
In this backward pass implementation, padded version of the output gradient tensor is needed to handle some edge cases. We are copying the essential information into a smaller array that stores only edge+padding information of the padded gradient array. This way, we don't need to copy and use the whole array during compute. This reduces the bandwidth requirement and speeds up the code. I don't know how common this operation is to have an TPP kernel of it's own.

2020-12-01 02:46 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
Why are these ops still used and not the intrinsiscs which come with LIBXSMM

2020-12-01 02:49 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/run.sh
>  export LD_LIBRARY_PATH=/nfs_home/nchaudh1/libxsmm/lib/        # Set LD_LIBRARY_PATH
Please make the path relative

2020-12-01 02:51 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +at::Tensor relu_forward_bf16(at::Tensor& input){
But what about the LIBXSMM TPPs?

2020-12-01 02:52 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
What are the sizes? Are they falling into the optimized path of the transposes?

2020-12-01 02:53 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for(int filter=0; filter < F_t; filter++){
Do you have a more detailed explanation what is needed in an abstract way then we can decide if a TPP is good.

2020-12-01 03:28 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
Yes. I need to update it. I couldn't find the code for TPPs that I should use. Can you send the link of the code where you have used them?

2020-12-01 03:35 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
The matrix size is M = 64 (Tile size), N = 15 (Number of filters). I don't know how to check if the optimized path is being used for transpose.

2020-12-01 05:54 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
intrinsics are here: 
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_intrinsics_x86.h#L647
and usage here:
https://github.com/hfp/libxsmm/blob/master/src/template/libxsmm_dnn_bf16_macros_define.tpl.c#L16

However, I believe with TPP the whole file is not needed

2020-12-01 06:41 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
Yes, you are right that I may not need this file at all.

2020-12-01 06:42 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
Is it possible to lose some accuracy if I switch from scaler transform to TPP based transform (in FP32)?

2020-12-01 22:57 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
only if it changes the order of your computation around them. they are just data movements and don't do any calculations on the the data.

2020-12-02 19:34 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Bfloat16.h
> +/* create a type called bfloat16 – need to figure out a common header file */
Replaced with TPP kernel for conversion and removed the header file. Resolving conversation for now. Let me know if you have any additional comment.

2020-12-02 19:35 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#include<libxsmm_intrinsics_x86.h>
I am using the TPP kernels now. So resolving this conversation too.

2020-12-02 19:36 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +void convert_f32_bf16(float* in, bfloat16* out, int len)
I use the TPP kernel for conversion now. Resolving this conversation.

2020-12-02 19:42 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
I am using the libxsmm_dispatch_meltw_copy() kernel for initialization of zeros now. I tried using the 2D version but it threw an error or did not run correctly (maybe because I am trying to initialize a submatrix). So, I ran 1xN implementation in the loop for M time to initialize and MxN array. This gave me 30-40% performance loss.

2020-12-02 19:45 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int channel = 0; channel < C_t; channel++){                 /* Loop for initilization of grad array */
Same issue with the initialization using libxsmm_dispatch_meltw_copy() kernel in a loop. 30-40% drop in performance.

2020-12-02 19:46 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/run.sh
>  export LD_LIBRARY_PATH=/nfs_home/nchaudh1/libxsmm/lib/        # Set LD_LIBRARY_PATH
The new commit has relative path. Resolving conversion now.

2020-12-02 19:50 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for (int channel=0; channel < C_t; channel++){
I could not find a TPP kernel that can change tensor layout/shape. Can you send me a link of a TPP kernel where you change the tensor layout/shape? I don't think I can use a transform kernel.

2020-12-02 19:56 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
I replaced the scaler transform with mateltwise transform kernel. But, my weight updates (after backward pass) are wrong sometimes. It is weird because sometimes the results of weight update match with MKLDNN layer and sometimes half of them don't match. This was not the case with my scaler transform kernel. The weights always matched with MKLDNN layer.

2020-12-02 20:15 UTC, egeor commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
Can you please let me know what is the error when you try the 2D approach? If you want to initialize a submatrix, you can do it by setting the proper LD.

2020-12-02 20:15 UTC, egeor commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int channel = 0; channel < C_t; channel++){                 /* Loop for initilization of grad array */
Same as above, can you please point to the JIT error?

2020-12-03 04:46 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
I have this configuration of Large Matrix and Submatrix.
Large Matrix - number of rows = 15, columns = 60000
Submatrix - number of rows = 15, columns = 64 (I need to transform this)
1st case (assuming row major layout) -  I set M = 15, N = 64 and ldo = 60000, ldi = NULL. This gives me a Seg fault error.
2nd case (assuming column major) - I set M = 64, N = 15 and ldo = 15, ldi=NULL. In this case the dispatch kernel returns a NULL pointer.

2020-12-03 05:59 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
you need to set the ldi I would guess as you have an input and an output matrix.

2020-12-03 06:18 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
But I am using this flag LIBXSMM_MELTW_FLAG_COPY_ZERO and not using any input matrix.  There is only an output matrix.

2020-12-04 02:31 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
I mean you need at least ldo for 2d.
@egeor : do we have a standalone tester for this?

2020-12-04 05:04 UTC, egeor commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
I believe the problem was some LD check, I fixed it in master. Please pull/rebuild; you should specify only ldo for the "zero" kernel. For future reference, please use LIBXSMM_VERBOSE=-1, this would reveal the error right away since the proper error message would be shown...

2020-12-07 05:55 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
I get wrong results with the VNNI Transform kernel. The parameters in use. I use LIBXSMM_MELTW_FLAG_TRANSFORM_NORM_TO_VNNI flag.
M = 464, N = 16, ldi = 60400, ldo = 512
Is this expected?

2020-12-07 20:02 UTC, alheinecke commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
Hmm,,, I used the harness (extended it to arbitrary ldi/ldo) in https://github.com/hfp/libxsmm/tree/master/samples/eltwise
./eltwise_transform V 2 464 16 60400 512
this one is giving correct results and also the assembly looks fine:
XDIS 0: DATAXFER  BASE       4C8B07                   mov r8, qword ptr [rdi]
XDIS 3: DATAXFER  BASE       4C8B4F08                 mov r9, qword ptr [rdi+0x8]
XDIS 7: DATAXFER  BASE       49C7C201000000           mov r10, 0x1
XDIS e: KMASK     AVX512VEX  C4C17B92CA               kmovd k1, r10d
XDIS 13: DATAXFER  BASE       49C7C201000000           mov r10, 0x1
XDIS 1a: KMASK     AVX512VEX  C4C17B92D2               kmovd k2, r10d
XDIS 1f: DATAXFER  BASE       48C7C200000000           mov rdx, 0x0
XDIS 26: BINARY    BASE       4883C202                 add rdx, 0x2
XDIS 2a: DATAXFER  BASE       48C7C000000000           mov rax, 0x0
XDIS 31: BINARY    BASE       4883C001                 add rax, 0x1
XDIS 35: DATAXFER  AVX512EVEX 62D1FF896F00             vmovdqu16 xmm0{k1}{z}, xmmword ptr [r8]
XDIS 3b: DATAXFER  AVX512EVEX 62D1FF896F88E0D70100     vmovdqu16 xmm1{k1}{z}, xmmword ptr [r8+0x1d7e0]
XDIS 45: DATAXFER  AVX512EVEX 62D1FF0A7F01             vmovdqu16 xmmword ptr [r9]{k2}, xmm0
XDIS 4b: DATAXFER  AVX512EVEX 62D1FF0A7F8902000000     vmovdqu16 xmmword ptr [r9+0x2]{k2}, xmm1
XDIS 55: BINARY    BASE       4983C002                 add r8, 0x2
XDIS 59: BINARY    BASE       4983C104                 add r9, 0x4
XDIS 5d: BINARY    BASE       483DD0010000             cmp rax, 0x1d0
XDIS 63: COND_BR   BASE       7CCC                     jl 0x31
XDIS 65: BINARY    BASE       4981C020AC0300           add r8, 0x3ac20
XDIS 6c: BINARY    BASE       4981C1C0000000           add r9, 0xc0
XDIS 73: BINARY    BASE       4883FA10                 cmp rdx, 0x10
XDIS 77: COND_BR   BASE       7CAD                     jl 0x26
XDIS 79: RET       BASE       C3                       ret 

0x1d0: 464
0x1d7e0: 120800

2020-12-08 10:28 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +#if defined(LIBXSMM_INTRINSICS_AVX512_CORE)
It is working after the race condition fix in my code. Changes added to latest commit. Resolving the conversation now.

2020-12-08 10:29 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int filter = 0; filter < F_t; filter++){                            /* Loop for initilization of output array */
It is working now. Changes added to latest commit. Resolving the conversation now.

2020-12-08 10:30 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +            for(int channel = 0; channel < C_t; channel++){                 /* Loop for initilization of grad array */
It is working now. No significant performance drop. Changes added to latest commit. Resolving the conversation now.

2020-12-08 10:30 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    libxsmm_xtransfunction trans_shortkernel_grad = get_tr_kernel(sizeof(float), short_W_t/2, F_t, F_t);      // Dispatch transpose kernel
It is working after the race condition fix in my code. Changes added to latest commit. Resolving the conversation now.

2020-12-09 04:31 UTC, alheinecke reviewed
Do I see it correctly that we need to close on the following items?: 
a) ReLU TPP still needs to be integrated
b) Padding TPP needs to be defined
c) identify which TPP with what problemsizes do negatively impact performance
d) getting rid of "USE_TPP" define

2020-12-09 08:28 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +    for(int kw = 0; kw < WW_t; kw++){                               // Loop to permute weight tensor dimensions
I used the transpose TPP and it is working now. I was able to use transpose TPP in place of all permute kernels. Changes present in the latest commit. Resolving conversation now.

2020-12-09 08:36 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for (int channel=0; channel < C_t; channel++){
I was able to use the transpose TPP kernels to permute dimensions. However, the weight kernel flip/reverse part required two loops. It is not clean as we are just increasing the amount of operations. Check out line 324-386 in Conv1dOpti.cpp file. 
Do we have a reverse copy kernel?   Something that does the following without a loop.
a1, a2, a3, a4, a5   -------------> a5, a4, a3, a2, a1

2020-12-09 10:59 UTC, narendrachaudhary51 commented
@alheinecke, I changed the permute loops into transform TPPs. 
a)  I am facing some error in relu due to the mask pointer type. I will apply it correctly and integrate it after correction.
b) Yes. I will define the virtual padding TPP. 
c) Currently, I do not see any performance drop. I made 20 iteration runs with and without TPP. The performance difference was 0.5-1% (or less) on cascade lake in FP32 run. So performance difference with TPP kernels seems negligible (atleast for the parameters that I use).     
d)  I will also remove USE_TPP after relu integration and checking everything.

2020-12-11 03:15 UTC, alheinecke commented
Was the ReLU is resolved, do you need @egeor 's help?

2020-12-11 11:20 UTC, narendrachaudhary51 commented
I just added the relu kernel. I am currently using the same TPP for both backward and forward pass (with backward flag). It is working for now. I have mentioned the error with FWD flag to @egeor.

2020-12-15 10:44 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for(int filter=0; filter < F_t; filter++){
Replaced the virtual padding loops with TPP kernels. Resolving the issue now.

2020-12-15 10:45 UTC, narendrachaudhary51 commented on samples/deeplearning/conv1dopti_layer/Conv1dOpti-extension/Conv1dOpti.cpp
> +        for (int channel=0; channel < C_t; channel++){
Resolving the issue for now.

2020-12-15 10:47 UTC, narendrachaudhary51 commented
I have replaced all the parts of existing code with TPP kernels. Now, I need to check the performance and remove USE_TPP define after that.

2020-12-15 18:52 UTC, alheinecke commented
great, thanks. Please let us know when done and then we can merge.

2021-01-04 06:37 UTC, narendrachaudhary51 commented
I made all the changes and removed the older non-TPP code. Code is ready for integration from my side.

2021-01-05 07:49 UTC, alheinecke approved these changes

2021-01-05 07:49 UTC, merged