Initial check-in. More routines are ready. This is just the first for the first test
hfp/libxsmm pull request #439
Opened 2020-12-11 19:19 UTC by gregmhenry

2020-12-14 15:40 UTC, alheinecke requested changes

2020-12-14 15:40 UTC, alheinecke commented on samples/encoder/compile
> +rm -rf xed
Please add default execution env sh/bash

2020-12-14 15:40 UTC, alheinecke commented on samples/encoder/compile
> +./mfile.py install
please add versioned binary for python

2020-12-14 15:40 UTC, alheinecke commented on samples/encoder/compile
> +icc -DNDEBUG -DLIBXSMM_OPENMP_SIMD -DXED_DECODE_TESTING -I. -I../../include -I../../src -I./xed/kits/xed-install-base/include -I./xed/kits/xed-install-base/examples -fPIC -g -Wall -diag-disable 1879,
this belongs into the libxsmm makefile

2020-12-14 15:40 UTC, alheinecke commented on samples/encoder/convert_int_to_name.c
> +#include <stdio.h>
This entire file should be removed, please use this existing routine instead: https://github.com/hfp/libxsmm/blob/master/src/generator_common.h#L1032

2020-12-14 15:40 UTC, alheinecke commented on samples/encoder/encoder_x86.c
> +/* #define XED_DECODE_TESTING */
Can you please move these routines into a file such that all XED related routines are in this file

2021-05-31 14:53 UTC, hfp commented
Shall we close this PR?

2021-07-07 06:54 UTC, alheinecke commented
Do we have a timeline on this?

2021-07-15 04:01 UTC, closed without merging