split csr2csc function
hfp/libxsmm pull request #481
Opened 2021-05-14 20:53 UTC by ashokei

2021-05-16 05:54 UTC, alheinecke requested changes
please see detailed comments

2021-05-16 05:54 UTC, alheinecke commented on samples/deeplearning/sparse_adagrad_fused/sparse_adagrad.cpp
> +  CTraceEvents::Scoped cevent("csr2csc", "", "", "", true);
why not using libxsmm timer which is available?

2021-05-16 05:54 UTC, alheinecke commented on samples/deeplearning/sparse_adagrad_fused/sparse_adagrad.cpp
> +#include "ctevents.h"
This include and our libraries needs to use are missing in this PR.

2021-05-18 03:55 UTC, ashokei commented on samples/deeplearning/sparse_adagrad_fused/sparse_adagrad.cpp
>    for(int i = 0; i < warmup; i++) {
saiusJK

2021-07-07 06:54 UTC, alheinecke commented
Is this still active and should be merged it has now additional conflicts.

2021-07-15 04:00 UTC, closed without merging