WIP: AVX2 Float 32x32 SP
hfp/libxsmm pull request #493
Opened 2021-06-23 23:59 UTC by deeptiag1

Submitting to get feedback on the blocking sizes. Thanks!

2021-06-24 00:26 UTC, alheinecke requested changes
I missed changes to following routine:
https://github.com/hfp/libxsmm/blob/master/src/generator_gemm_common.c#L1565
so everything requiring masking won't work.

2021-06-24 00:26 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    // if ( i_xgemm_desc->m >= 64 ) {
Please use C comments and not C++ comments

2021-06-24 00:26 UTC, alheinecke commented on src/generator_common.c
> +  *o_range_1 = l_N1; //78
not sure, why these comments are there, please use C comments instead of C++ if these comments are temp. needed

2021-06-24 00:26 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +      if ( l_m_blocking % 8 != 0 ) {
that should be mod 4

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +/*
not sure why this code was added as comment

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
>        if ( io_generated_code->arch < LIBXSMM_X86_AVX512) {
I would change this one to < LIBXSMM_X86_AVX512_VL256

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +      if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
Then this one can be removed

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +    if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
see above

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +    if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
see above

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +  if (( io_generated_code->arch >= LIBXSMM_X86_AVX512 ) || ( io_generated_code->arch >= LIBXSMM_X86_AVX512_VL256 )) {
see above >= LIBXSMM_X86_AVX512_VL256 incl.  >= LIBXSMM_X86_AVX512

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +                                       const int               i_displacement,// ((l_n * i_xgemm_desc->ldc) + (l_m * (i_micro_kernel_config->vector_length))) * (i_micro_kernel_config->datatype_size_o
please remove comments when no longer needed

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +  if ( (io_generated_code->arch < LIBXSMM_X86_AVX512) && (io_generated_code->arch != LIBXSMM_X86_AVX512_VL256) && (i_mask_reg_number != 0) ) {
Just change LIBXSMM_X86_AVX512 to LIBXSMM_X86_AVX512_VL256

2021-06-24 00:26 UTC, alheinecke commented on src/generator_x86_instructions.c
> +      //Change by D-
is here a change missing as there is only comment about a change, but not change?

2021-06-24 00:26 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    }
F64 branch for AVX512_VL256 seems to be missing

2021-06-24 00:26 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    if ( i_arch >= LIBXSMM_X86_AVX512_VL256) { // change by D-
special handling for int8 and bf16 seems to be missing in the subsequent lines, can be fixed later

2021-06-24 06:06 UTC, alheinecke requested changes
see further comments

2021-06-24 06:06 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  } else if ( ( i_arch <= LIBXSMM_X86_AVX512_VL256 ) && ( ( LIBXSMM_GEMM_PRECISION_F32  == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) )  ||
<= looks suspicious, should be ==

2021-06-24 06:06 UTC, alheinecke commented on src/generator_gemm.c
> -  } else if ( ( io_generated_code->arch <= LIBXSMM_X86_AVX512_VL256 ) && LIBXSMM_GEMM_PRECISION_F64 == LIBXSMM_GETENUM_INP( l_xgemm_desc_mod.datatype ) ) {
why was this removed? That looked right, perhaps == instead of <=?

2021-06-24 06:06 UTC, alheinecke commented on src/generator_gemm.c
> +  } else if ( ( io_generated_code->arch <= LIBXSMM_X86_AVX512_VL256 ) && LIBXSMM_GEMM_PRECISION_F32 == LIBXSMM_GETENUM_INP( l_xgemm_desc_mod.datatype ) ) {
check for VL256 should before general AVX512 checks as it was before.

2021-06-24 08:55 UTC, sbhatta3 commented on src/generator_gemm.c
> +  } else if ( ( io_generated_code->arch <= LIBXSMM_X86_AVX512_VL256 ) && LIBXSMM_GEMM_PRECISION_F32 == LIBXSMM_GETENUM_INP( l_xgemm_desc_mod.datatype ) ) {
fixed

2021-06-24 08:56 UTC, sbhatta3 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    }
added

2021-06-24 08:59 UTC, sbhatta3 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  } else if ( ( i_arch <= LIBXSMM_X86_AVX512_VL256 ) && ( ( LIBXSMM_GEMM_PRECISION_F32  == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) )  ||
fixed

2021-06-24 09:01 UTC, sbhatta3 commented on src/generator_gemm.c
> -  } else if ( ( io_generated_code->arch <= LIBXSMM_X86_AVX512_VL256 ) && LIBXSMM_GEMM_PRECISION_F64 == LIBXSMM_GETENUM_INP( l_xgemm_desc_mod.datatype ) ) {
added back

2021-06-24 09:03 UTC, sbhatta3 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  } else if ( ( i_arch <= LIBXSMM_X86_AVX512_VL256 ) && ( ( LIBXSMM_GEMM_PRECISION_F32  == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) )  ||
fixed

2021-06-24 09:05 UTC, sbhatta3 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  } else if ( ( i_arch <= LIBXSMM_X86_AVX512_VL256 ) && ( ( LIBXSMM_GEMM_PRECISION_F32  == LIBXSMM_GETENUM_OUT( i_xgemm_desc->datatype ) )  ||
would be good to move it up, right after LIBXSMM_X86_AVX2 check.

2021-06-24 09:07 UTC, sbhatta3 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +      if ( l_m_blocking % 8 != 0 ) {
fixed

2021-06-24 23:57 UTC, deeptiag1 commented
Following changes in this  [6679b23] commit:
1. Incorporated @alheinecke  feedback.
2. Removed C++ styled comments.
3. Tested  I16I32, USI8I32, SUI8I32, SUI8UI8 for NN_EQLD sizes.  
4. BF16F32, BF16, BF1632_FLAT, BF16_FLAT works for sizes <= 32x32.

Next Steps: 
1. I16I32, USI8I32, SUI8I32, SUI8UI8  datatypes needs to be tested for following use case:
      - NN_GTLD
      - NT_EQLD
      - NT_GTLD
2.  Enable BF16 for sizes BF16F32, BF16, BF1632_FLAT, BF16_FLAT >32x32 and fix masking issues.

2021-06-25 00:40 UTC, deeptiag1 commented on src/generator_common.c
> +  *o_range_1 = l_N1; //78
Removed comments.

2021-06-25 00:42 UTC, deeptiag1 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    // if ( i_xgemm_desc->m >= 64 ) {
Removed comments

2021-06-25 00:44 UTC, deeptiag1 commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    if ( i_arch >= LIBXSMM_X86_AVX512_VL256) { // change by D-
Int8 and Bf16 still works with the existing if conditions. I am not sure new check is required here.

2021-06-25 00:44 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +/*
Removed

2021-06-25 00:44 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +                                       const int               i_displacement,// ((l_n * i_xgemm_desc->ldc) + (l_m * (i_micro_kernel_config->vector_length))) * (i_micro_kernel_config->datatype_size_o
Removed

2021-06-25 00:44 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +  if ( (io_generated_code->arch < LIBXSMM_X86_AVX512) && (io_generated_code->arch != LIBXSMM_X86_AVX512_VL256) && (i_mask_reg_number != 0) ) {
Fixed

2021-06-25 00:45 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +      //Change by D-
I had added an change but reverted it, so this was a bad comment. Removed it

2021-06-25 00:45 UTC, deeptiag1 commented on src/generator_x86_instructions.c
>        if ( io_generated_code->arch < LIBXSMM_X86_AVX512) {
Fixed

2021-06-25 00:45 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +      if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
Removed

2021-06-25 00:46 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +    if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
Changed as per feedback

2021-06-25 00:46 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +    if ( io_generated_code->arch == LIBXSMM_X86_AVX512_VL256) {
Changed as recommended

2021-06-25 00:46 UTC, deeptiag1 commented on src/generator_x86_instructions.c
> +  if (( io_generated_code->arch >= LIBXSMM_X86_AVX512 ) || ( io_generated_code->arch >= LIBXSMM_X86_AVX512_VL256 )) {
Changed as recommended

2021-06-26 21:17 UTC, deeptiag1 commented
Closing this pull request, Thanks for the feedback!

2021-06-26 21:17 UTC, closed without merging