Resnet-50 implementation with ring buffers
hfp/libxsmm pull request #497
Opened 2021-07-23 20:06 UTC by taknevski

Includes 48 back-to-back layer invocations of Resnet50 with ring buffers. 
Includes per layer as well as network timing results.

2021-07-24 05:00 UTC, alheinecke requested changes
This PR is already in very good shape... only some minor issues requested.

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    {7, 7, 512, 2048, 1, 1, 0, 0, 0, 0, 1}, {7, 7, 2048, 512, 1, 1, 0, 0, 1, 1, 1}, {7, 7, 512, 512, 3, 3, 1, 1, 0, 0, 1},
it might be good to try also output padding for 3x3 and then input padding for the following 1x1.... then we can easily loop over all pixels in the 3x3

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +int main(int argc, char* argv[]) {
Can you please add parameter on the commandline for minibatch, activation format (LIBXSMM or NHWC), filter format (LIBXSMM or RSCK) and if ring-buffer should be used.

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +  libxsmm_dnn_fullyconnected_desc fullyconnected_desc;
lines 75 - 80 and gradient buffers can be deleted

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +  libxsmm_dnn_tensor* libxsmm_act[2];
we should have an option to have all layers (means 49 activation buffers), see above commandline option

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    conv_desc.buffer_format = LIBXSMM_DNN_TENSOR_FORMAT_NHWC;
here we would read the command line option for layouts

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    conv_desc.options = LIBXSMM_DNN_CONV_OPTION_OVERWRITE;
We only need overwrite

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +      max_act_size = MB * (ifh + 2 * pad_h_in) * (ifw + 2 * pad_w_in) * ifm * sizeof(float);
let's track activation size for layers, such that we can also run without ringbuffers

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    if (i % 2 == 0) {
see above additional if pass for 49 activation buffers

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    scratch_size = libxsmm_dnn_get_scratch_size(libxsmm_conv_layers[i], LIBXSMM_DNN_COMPUTE_KIND_ALL, &status);
this seems like a bug to me: instead we should track the scratch allocation overall layers, calculate the MAX, allocate it and then set this scratch pointer to all 48 conv handles

2021-07-24 05:00 UTC, alheinecke commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    l_start = libxsmm_timer_tick();
can you please try per layer training... e.g something along these lines "double per_layer_time[iters][48]"  and then within the openmp region you would do "if (tid == 0) { l_end = libxsmm_timer_tick(); per_layer_time[j][i] = libxsmm_timer_duration(per_layer_time[j][i-1], l_end); }"

When using this strategy, we don't start 48 parallel regions. Perhaps we can do both timeings: a) the current timing with 48 openmp regions and the one with only one region.

2021-07-27 18:17 UTC, taknevski commented on samples/deeplearning/cnnlayer/resnet_driver_f32.c
> +    {7, 7, 512, 2048, 1, 1, 0, 0, 0, 0, 1}, {7, 7, 2048, 512, 1, 1, 0, 0, 1, 1, 1}, {7, 7, 512, 512, 3, 3, 1, 1, 0, 0, 1},
This resulted in a segfault probably because the sizes for the activation(input_act_size, output_act_size) is somehow wrong

2021-07-27 18:39 UTC, alheinecke approved these changes

2021-07-27 18:39 UTC, merged