AVX512VL enabling
hfp/libxsmm pull request #509
Opened 2021-09-03 16:40 UTC by deeptiag1

2021-09-06 23:11 UTC, alheinecke requested changes

2021-09-06 23:11 UTC, alheinecke commented on src/generator_gemm_common.c
> +  if ( ( io_generated_code->arch >= LIBXSMM_X86_AVX512_VL256 ) && ( io_generated_code->arch <= LIBXSMM_X86_ALLFEAT ) ) {
Hmm.... There are a lot diffs here which make no sense in the file... Is this a git displaying issue?

2021-09-06 23:11 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +        && io_generated_code->arch != LIBXSMM_X86_AVX512_VL256_CPX && io_generated_code->arch <= LIBXSMM_X86_ALLFEAT ) {
This change seems to be a no-op

2021-09-06 23:11 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +      if (io_generated_code->arch < LIBXSMM_X86_AVX512_VL256) {
KNL/KNM not handled correctly

2021-09-06 23:11 UTC, alheinecke commented on src/generator_mateltwise_reduce_avx_avx512.c
> +      if (io_generated_code->arch < LIBXSMM_X86_AVX512_VL256) {
KNL/KNM not handled correctly

2021-09-06 23:11 UTC, alheinecke commented on src/libxsmm_dnn.c
> +#endif
Minor issue.. all caps with LIBXSMM_ with prefix for defines would be great.

2021-09-06 23:11 UTC, alheinecke commented on src/libxsmm_dnn_convolution_forward.c
>  libxsmm_dnn_err_t libxsmm_dnn_convolve_st_fwd_custom_custom_f32_f32(libxsmm_dnn_layer* handle, int start_thread, int tid)
I'm not sure about the intrsinics tests... It's technically still AVX512... so I would not change this.

2021-09-06 23:11 UTC, alheinecke commented on include/libxsmm_intrinsics_x86.h
> +#       if (LIBXSMM_X86_AVX512_VL256 <= LIBXSMM_MAX_STATIC_TARGET_ARCH)
I would not add these intrinsics version, as we technically need full AVX512 support of the compiler, but later in convolutions this intrinsics are used as well. (see further down below).

2021-09-07 13:32 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +      if (io_generated_code->arch < LIBXSMM_X86_AVX512_VL256) {
This change was not intended for m8 Blocking. I will revert it back. Eltwise changes still needs to be tested!

2021-09-07 13:32 UTC, deeptiag1 commented on src/generator_mateltwise_reduce_avx_avx512.c
> +      if (io_generated_code->arch < LIBXSMM_X86_AVX512_VL256) {
This change was not intended for m8 Blocking. I will revert it back. Eltwise changes still needs to be tested!

2021-09-07 14:02 UTC, deeptiag1 commented on src/generator_gemm_common.c
> +      /* we add when scaling during conversion to FP32 */
The comment is misleading here. It is BF16 change.

2021-09-22 04:40 UTC, merged