WIP: Aarch64 eltwise Binary and Unary simple ops enabling
hfp/libxsmm pull request #519
Opened 2021-09-28 14:38 UTC by deeptiag1

Fixed CI issues.
Enabled Binary and Unary simple ops

2021-09-28 15:10 UTC, alheinecke requested changes
It seems in generator_mateltwise_aarch64.c merge conflicts have been handled incorrectly that led to disabling the transposes and binary was not added properly.

It seems this was not found as the unit tests have not been extended to all the binary & unary functions which are added with this PR. Please add the unit tests (ala copy and transpose in kernel_test_aarch64, can be looked at how copy was created from the x86 test) and add all of these tests to run_test_aarch64.sh

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    } else if ( LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype ) ) {
Please add this back

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    } else if ( LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_INP( i_mateltwise_desc->datatype ) ) {
Please add this back

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    } else if ( LIBXSMM_DATATYPE_BF16 == LIBXSMM_GETENUM_OUT( i_mateltwise_desc->datatype ) ) {
Please add this back

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    } else if ( LIBXSMM_DATATYPE_I16 == LIBXSMM_GETENUM_OUT( i_mateltwise_desc->datatype ) ) {
Please add this back

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    if (i_mateltwise_desc->operation == LIBXSMM_MELTW_OPERATION_UNARY ) {
Please revert this change, you also need to add a branch for Binary... please have a look at the x86 code as template

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_aarch64.c
> -    if (i_mateltwise_desc->operation == LIBXSMM_MELTW_OPERATION_UNARY ) {
Please revert this change, you also need to add a branch for Binary... please have a look at the x86 code as template

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +  if( bcast_input == 0 ) {
please wrap the offset calculation

2021-09-28 15:10 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +  if( ( bcast_input == 0) || (( bcast_col == 1 ) & (in == 0)) ) {
Please wrap the offset calculation

2021-09-28 18:08 UTC, alheinecke commented
code looks good, please add the unit tests, check them and then we can merge

2021-09-28 18:09 UTC, alheinecke commented on src/generator_mateltwise_unary_binary_aarch64.c
> +  if( bcast_input == 0 ) {
this is still open I guess

2021-09-29 17:21 UTC, alheinecke reviewed
Are now all unit tests passing?

2021-09-29 17:47 UTC, deeptiag1 commented
FMULADD(Binary) and Unary(Inc) is left. Test pass for rest of them.

2021-09-29 17:55 UTC, alheinecke commented
OK, let me know when done, then I can merge

2021-09-29 20:42 UTC, alheinecke approved these changes

2021-09-29 20:42 UTC, merged