Fix BF16 CPX code
hfp/libxsmm pull request #550
Opened 2021-11-07 00:24 UTC by deeptiag1

Tested for following:
 cpx BF16  , cpx SP  ,cpx DP  , cpx BF16F32  , clx BF16, clx BF16F32

2021-11-07 02:03 UTC, alheinecke requested changes
one change looks fishy and can you please exclude all changes to mateltwise/matequation from this PR?

2021-11-07 02:03 UTC, alheinecke commented on src/generator_gemm_avx512_microkernel.c
> +        } else if (LIBXSMM_GEMM_PRECISION_BF16 == LIBXSMM_GETENUM_INP( i_xgemm_desc->datatype )) {
this change looks fishy... what is the original code doing?

2021-11-07 02:48 UTC, deeptiag1 commented on src/generator_gemm_avx512_microkernel.c
> +        } else if (LIBXSMM_GEMM_PRECISION_BF16 == LIBXSMM_GETENUM_INP( i_xgemm_desc->datatype )) {
This change is reverting the  code state  to original code. 
Original Code is doing the same thing https://github.com/hfp/libxsmm/blob/d46a8f2f0104d82fd37d6e157ebab0e39be1b7fb/src/generator_gemm_avx512_microkernel.c#L1442.

2021-11-07 03:37 UTC, alheinecke commented
OK, then after removal of the eltwise stuff, this can be merged

2021-11-09 04:22 UTC, deeptiag1 commented
Reverted eltwise changes

2021-11-09 06:08 UTC, alheinecke requested changes
very minor change

2021-11-09 06:08 UTC, alheinecke commented on src/generator_mateltwise_misc_avx_avx512.c
> +        if  (io_generated_code->arch < LIBXSMM_X86_AVX512_CPX) {
can you please revert this file as well?

2021-11-09 06:45 UTC, deeptiag1 commented on src/generator_mateltwise_misc_avx_avx512.c
> +        if  (io_generated_code->arch < LIBXSMM_X86_AVX512_CPX) {
Done!

2021-11-09 18:13 UTC, alheinecke approved these changes

2021-11-09 18:14 UTC, merged