Enabling transpose of A in GEMM via an intermediate transpose on the stack
hfp/libxsmm pull request #564
Opened 2021-11-28 07:43 UTC by kvoronin-intel

Summary:
Adding a stack transpose as a means to enable GEMM with trans_a = 1. For transposing on the stack, meltwise transform generator is used. Currently only for SP, AVX512.

Note:
A not-really-clean version to initiate a code review and understand what should be the desired final state (hoisting the changes to libxsmm_generator_gemm_kernel if we want to enable trans_a for a wider configuration scope?).

Testing:
Code has been only tested for functional correctness on just a couple of problems with square and rectangular A. More will be needed before merging.

2021-11-29 01:34 UTC, alheinecke commented
after the github outage I have rebased the PR to the a_transpose branch on upstream (just copy of latest master for now) and I do detailed review later.

2021-11-30 00:29 UTC, alheinecke requested changes
LGTM, some minor comments such that x86 and FP32 and FP64 could use the feature should be added.

2021-11-30 00:29 UTC, alheinecke commented on include/libxsmm_generator.h
> +#define LIBXSMM_GEMM_NO_BYPASS(FLAGS, ALPHA, BETA) (1)
I think we should only remove the transpose A check

2021-11-30 00:29 UTC, alheinecke commented on samples/xgemm/kernel.c
> -    unsigned int l_keep_going = 0;
perhaps we should think about fixing this better than the trans_b stuff, otherwise we implement the same stuff 4x times

2021-11-30 00:29 UTC, alheinecke commented on samples/xgemm/kernel_jit_exec.h
> +#define A_TRANS_ENABLED
I guess we can remove this.

2021-11-30 00:29 UTC, alheinecke commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
Maybe checking against exactly: 
(l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) == LIBXSMM_GEMM_FLAG_TRANS_A)

Also we should check for now not only on FP32, but also that no Batch Reduce GEMM is used (also flag fields). In the moment a Batch reduce flag is set we should error out for now. It's simple to add, but we need to transpose several a matrices and mock with more inputs and pointers....

2021-11-30 00:29 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> -LIBXSMM_API_INTERN void libxsmm_generator_gemm_sse_avx_avx2_avx512_kernel( libxsmm_generated_code*        io_generated_code,
The first 100 lines look pretty messy in the diff. I think it's fine, but perhaps you double and do a commit which has a cleaner diff?

2021-11-30 00:29 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +  unsigned int lda_transpose = i_xgemm_desc->m;
starting here the diff gets clean.

2021-11-30 00:29 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel( io_generated_code, &l_loop_label_tracker,
here we should add an arch-checker

2021-11-30 05:17 UTC, kvoronin-intel commented on include/libxsmm_generator.h
> +#define LIBXSMM_GEMM_NO_BYPASS(FLAGS, ALPHA, BETA) (1)
I got a bit confused by the existing check.
Independent of transpose A check, if, say, alpha != 1, then LIBXSMM_FEQ(1,alpha) will be 0 and the check will be true as we compare righthand side to 0. 
But it is used in expressions like this one
```
 if  (LIBXSMM_GEMM_NO_BYPASS(flags, alpha, beta)
    && ... )
  {
    ...
    LIBXSMM_GEMM_DESCRIPTOR(...);
  }
```
So if the check intended to bail out if alpha != 1 (which I think it was), it wasn't doing that. Of course, it can be fixed by changing FEQ to NEQ and swapping && with ||.
But am I correct here?

2021-11-30 05:19 UTC, kvoronin-intel commented on samples/xgemm/kernel.c
> -    unsigned int l_keep_going = 0;
Sure, will reduce the code duplication. I had same exact thought but looked at trans_b stuff and decided to use the same boilerplate approach.

2021-11-30 05:22 UTC, kvoronin-intel commented on samples/xgemm/kernel_jit_exec.h
> +#define A_TRANS_ENABLED
removed

2021-11-30 05:31 UTC, kvoronin-intel commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
I'll add a check for F32.
Checking for exact match with `LIBXSMM_GEMM_FLAG_TRANS_A` will exclude possibility of modifiers like LIBXSMM_GEMM_FLAG_ALIGN_A and LIBXSMM_GEMM_FLAG_ALIGN_C, LIBXSMM_GEMM_FLAG_ALIGN_C_NTS_HINT + some cobinations. 
Is it ok to disable those (by making an exact match for TRANS_A)?

2021-11-30 06:35 UTC, kvoronin-intel commented on samples/xgemm/kernel_jit_exec.h
> +#define A_TRANS_ENABLED
Removed

2021-11-30 06:36 UTC, kvoronin-intel commented on src/generator_gemm_sse_avx_avx2_avx512.c
> -LIBXSMM_API_INTERN void libxsmm_generator_gemm_sse_avx_avx2_avx512_kernel( libxsmm_generated_code*        io_generated_code,
Removed unnecessary code shuffling so that the diff looks much cleaner.

2021-11-30 06:58 UTC, kvoronin-intel commented on samples/xgemm/kernel.c
> -    unsigned int l_keep_going = 0;
Attempted to unite the code for trans_a, as well as trans_b, in case of SP. Is this better?

2021-11-30 07:03 UTC, kvoronin-intel commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel( io_generated_code, &l_loop_label_tracker,
do you want to have a dispatch here and call appropriate microkernels? i see there exist at least _sse, _avx and _spr/_pre_spr microkernels which could be called along with _avx512 at this place [unless there are subtle reasons why some of them cannot be called in the same way as _avx512 is now].

2021-11-30 16:44 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel( io_generated_code, &l_loop_label_tracker,
yes, a dispatch for sse, avx and avx512 (as it is right now). the deeper specializing for avx512 pre/post Golden Cove core is done internally.

2021-11-30 16:48 UTC, alheinecke reviewed
Thanks, very nice!

I think we only thing missing the guarding for batch reduce and the sse/avx/avx512 dispatch

2021-11-30 16:48 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> -LIBXSMM_API_INTERN void libxsmm_generator_gemm_sse_avx_avx2_avx512_kernel( libxsmm_generated_code*        io_generated_code,
Thanks this looks very good now.

2021-11-30 16:50 UTC, alheinecke commented on include/libxsmm_generator.h
> +#define LIBXSMM_GEMM_NO_BYPASS(FLAGS, ALPHA, BETA) (1)
The check is correct now. It should bail out if alpha != 1 and if beta != 0 or != 1.... in other words we can only JIT kernel if alpha == 1 and if beta is either 0 or 1

2021-11-30 16:51 UTC, alheinecke commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
These are independent flags, we really only want to check that one bit.

2021-12-06 04:11 UTC, kvoronin-intel commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
Right, mixed up smth aabout the flags. Added a check for FP32 and BRGEMM. Is `LIBXSMM_ERR_INVALID_GEMM_CONFIG` an appropriate error for the unsupported cases here?

2021-12-06 04:30 UTC, kvoronin-intel commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel( io_generated_code, &l_loop_label_tracker,
Added a dispatch, quickly checked additionally for avx, avx2 and sse42 that code is visually correct. For p4p (after adding export LIBXSMM_TARGET=x86_64) a simple test worked as well.

2021-12-06 04:34 UTC, kvoronin-intel commented
> Thanks, very nice!
> 
> I think we only thing missing the guarding for batch reduce and the sse/avx/avx512 dispatch

Great! What are the testing guidelines in general? Is there a dedicated test suite, or standard set of testing configurations to extend for trans_a & test? So far I only added a small test in samples/xgemm

2021-12-08 07:12 UTC, alheinecke commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
yes!

2021-12-08 07:13 UTC, alheinecke commented
in kernel_test (in the same directory) we have some scripts which draw random dimension. They should be adopted for A Trans and then we are good.

2021-12-18 07:12 UTC, kvoronin-intel commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
Did a change with `LIBXSMM_ERR_INVALID_GEMM_CONFIG`.
But, when I run, e.g. the kernel_test with some flavour of BRGEMM, the error with LIBXSMM_VERBOSE=-1 would look like:
"JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!
LIBXSMM ERROR (libxsmm_generator_gemm_kernel): invalid GEMM config in setup detected (error #90035)!"
Is it better than throwing `LIBXSMM_ERR_LDA_TRANS` which will give a more transpose-specific message
"GEMM kernel with trans A requested, but target/datatype not supported (error ...)"?

2021-12-18 07:14 UTC, kvoronin-intel commented on samples/xgemm/kernel_test/sgemm_tn_eqld.slurm
> +TESTFILE1=$(mktemp -p .)
Added a standard test for sgemm_tn, with "eq" and "gt" cases for leading dimensions.

2021-12-20 17:52 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel( io_generated_code, &l_loop_label_tracker,
great

2021-12-20 17:53 UTC, alheinecke commented on samples/xgemm/kernel_test/sgemm_tn_eqld.slurm
> +TESTFILE1=$(mktemp -p .)
great

2021-12-20 17:56 UTC, alheinecke commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
Yeah, you are right let's add a specific error code, perhaps even just for BRGEMM. BRGEMM could use the discussed gather & and inner product version though. Later on we can just put all A_i matrices on the stack, transpose them ( \forall A'_i = trans(A_i) and then feed the new A'_i into the BRGEMM.

2021-12-20 17:59 UTC, alheinecke reviewed
LGTM, if think after your suggestion with having a different error code we can merge this back into the a_transpose branch

2021-12-20 20:50 UTC, kvoronin-intel commented on src/generator_gemm.c
> +  if ( (l_xgemm_desc_mod.flags & LIBXSMM_GEMM_FLAG_TRANS_A) > 0 ) {
Added a new error code, so that now the output for BRGEMM flavors looks like this:
`JIT failed, please run with LIBXSMM_VERBOSE=-1 and/or with debug mode LIBXSMM library!
LIBXSMM ERROR (libxsmm_generator_gemm_kernel): BRGEMM is not supported for the specified configuration with A transpose (error #90048)!`
Let me know if you had in mind a more general error like "Unsupported GEMM configuration for BRGEMM case" or smth.

2021-12-30 16:39 UTC, alheinecke commented
I have just move the latest master into the branch. It has following changes:
- new GEMM frontend, which should not matter for you: https://github.com/hfp/libxsmm/blob/master/src/generator_gemm_sse_avx_avx2_avx512.c#L174, the transpose code goes just after this new block as this is just setting up the input registers in a different way. (I also move to the open stream up into another function but that shouldn't matter).
- we got rid of LIBXSMM_GEMM_PRECISION and everything is now LIBXSMM_DATATYPE, this is just very simple renaming, but has to be done in the lines coming in from PR, e.g.: LIBXSMM_GEMM_PRECISION_F32 is now LIBXSMM_DATATYPE_F32.
(for your reference the full diff of changes in master: https://github.com/hfp/libxsmm/commit/cdb895a3cbd38b414f5420617be46132fa082155 )

2021-12-31 17:41 UTC, alheinecke commented
I have heavily refactored the kernel.c and kernel_parallel.c performance tester to be weakly typed. That removed 4K LoC Spaghetti code, so testing for trans_a should be much easier now.

2022-01-03 03:22 UTC, kvoronin-intel commented
> I have heavily refactored the kernel.c and kernel_parallel.c performance tester to be weakly typed. That removed 4K LoC Spaghetti code, so testing for trans_a should be much easier now.

I've rebased the branch onto the current master, the tests are passing now.

2022-01-14 00:59 UTC, kvoronin-intel commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +      libxsmm_generator_gemm_getval_stack_var( io_generated_code, &l_micro_kernel_config, LIBXSMM_GEMM_STACK_VAR_TRANSPOSE_PTR, LIBXSMM_X86_GP_REG_R9 );
Here we set r9 (input for the meltwise = transpose) to the allocated space on the stack via the new API.

2022-01-14 01:00 UTC, kvoronin-intel commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +        libxsmm_x86_instruction_alu_imm( io_generated_code, LIBXSMM_X86_INSTR_ADDQ, LIBXSMM_X86_GP_REG_RSP, l_trans_a_stack_size );
Clean-up here is done also under condition that the new API is not useed.

2022-01-14 01:01 UTC, kvoronin-intel commented
@alheinecke, @egeor I've rebased the stack-transpose branch onto the latest enable_gemms_in_eqs branch. To me it all went smoothly, but please have a look (especially @egeor).

2022-01-14 01:05 UTC, kvoronin-intel commented on src/generator_gemm_common.c
> +      return -96;
Decided to introduce a new pointer for the stack structure rather than re-use some other buffer (like "eltwise buf1"). The rationale is that I'm afraid of nasty bugs which can appear in the future in case some new thing will need "eltwise buf1" for both eltwise and transpose.
If you're confident that this will never be the case and we can safely re-use one of the existing pointers instead of creating `LIBXSMM_GEMM_STACK_VAR_TRANSPOSE_PTR`, let me know.

2022-01-14 04:42 UTC, egeor commented on src/generator_gemm_common.c
> +      return -96;
Sounds good -- definitely this is better approach as we discussed.

2022-01-14 04:45 UTC, egeor commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    if ( ((LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI & i_xgemm_desc->flags) != LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI) ) {
This should be fine since the stack manipulation infrastructure "requires" the new API

2022-01-14 05:16 UTC, egeor commented
@kvoronin-intel  This is an enhancement rather a change request:
Now the code allocates scratch in stack, transposes A there and uses the transposed A for the rest of the kernel.
This is all good, but with the new *ext API we support also generic ops on A/B before the xgemm:

https://github.com/hfp/libxsmm/blob/enable_gemm_in_eqs/include/libxsmm_typedefs.h#L919

So basically:
Ap = unary( A ) where the unary A may be transpose. In this case, if store_ap is set, the user provides a pointer where Ap should be saved (in this case the transposed A).

https://github.com/hfp/libxsmm/blob/enable_gemm_in_eqs/include/libxsmm_typedefs.h#L894

I believe with minimal changes you should be able to extend the current implementation as follows:
*  when the new *ext API is used and Ap = trans( A )  is requested you can use the equivalent logic as if LIBXSMM_GEMM_FLAG_TRANS_A was set (i.e. what you did) 

*  when the new *ext API is used and Ap = trans( A )  is requested, and *store_ap* is set, then instead of allocating scratch in stack, you should be able to use directly that user-provided pointer (e.g. by merely setting that proper ap pointer in the stack var LIBXSMM_GEMM_STACK_VAR_TRANSPOSE_PTR :) ). This is important in the context of building higher level contractions with this microkernel... Think of a large GEMM with transpose A. The user would block the loops and use the trans_A xgemm microkernel only the first time the "input/original A" panels are touched. In the rest iterations the user would use regular (non trans A) microkernels by reusing the transposed A from the provided buffer. This is crucial to get high performance A^T x B ops (since the transposed tensor will be reused/the transposed cost will be amortized).

Not sure if you want to do this in a different PR or update the current one.

2022-01-14 05:27 UTC, alheinecke commented
These suggestions are good, but orthogonal. A^T, B^T, C^T, A_VNNI, B_VNNI, C_VNNI need support without using the EXT API and can be implemented using EXT API as well. 
This PR enables some A^T on to of the B^T we already have. So in the end we will several changes to enable both cases and even combinations: In the EXT API we can have unary on A which is computing exp(A) and we can have the A^T flag being set.

2022-01-14 05:45 UTC, alheinecke requested changes

2022-01-14 05:45 UTC, alheinecke commented on src/generator_gemm.c
> +    // Neither non-FP32 nor BRGEMM are supported for the trans_a = 1 case
please use C89 comments ( /* */ ) instead of C++ comments ( // )

2022-01-14 05:45 UTC, alheinecke commented on src/generator_gemm_common.c
> +  if ( ((LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI & i_xgemm_desc->flags) == LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI) &&
Why is this guarded for EXT_ABI

2022-01-14 05:45 UTC, alheinecke commented on src/generator_gemm_common.c
> +   *      Transpose A ptr                           <-- RBP-96, RSP
it seems the list of variables in the comment is not aligned with the case statement, however, this is more issue in base and not in this PR (@egeor)

2022-01-14 18:03 UTC, kvoronin-intel commented on src/generator_gemm_common.c
> +  if ( ((LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI & i_xgemm_desc->flags) == LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI) &&
Good question. I've taken it from gemm scratch allocation a couple of lines above https://github.com/hfp/libxsmm/blob/enable_gemm_in_eqs/src/generator_gemm_common.c#L799

Main reason for doing so was that I was unsure whether we intend calling `libxsmm_generator_gemm_setup_stack_frame_allocate_scratch()` only when EXT_ABI is enabled or not.
On one hand, we are checking for this outside the call in https://github.com/hfp/libxsmm/blob/enable_gemm_in_eqs/src/generator_gemm_sse_avx_avx2_avx512.c#L214.
On the other hand, I saw this check in the function `libxsmm_generator_gemm_setup_stack_frame_allocate_scratch()` as well.

As long as we check in generator_gemm_sse_avx_avx2_avx512.c, I can definitely remove the check inside `..._allocate_scratch`.

2022-01-14 18:13 UTC, egeor commented on src/generator_gemm_common.c
> +  if ( ((LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI & i_xgemm_desc->flags) == LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI) &&
The idea (before the A trans work) is that the the "zmm scratch" *would* be used only with the new EXT_ABI (since otherwise we wouldn't fuse anything in the first place). 

The libxsmm_generator_gemm_setup_stack_frame_allocate_scratch is intended to be called  either when we have SPR kernel (since we need that gemm scratch for dumping the tiles/downconvert) or when we have EXT_ABI (fusion in xgemm). This is why those conditions were there in the first place.

2022-01-14 18:16 UTC, kvoronin-intel commented on src/generator_gemm.c
> +    // Neither non-FP32 nor BRGEMM are supported for the trans_a = 1 case
Fixed

2022-01-14 18:20 UTC, kvoronin-intel commented on src/generator_gemm_common.c
> +  if ( ((LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI & i_xgemm_desc->flags) == LIBXSMM_GEMM_FLAG_USE_XGEMM_EXT_ABI) &&
Thanks for the explanation @egeor, I'm removing the check for the transpose scratch here then. Only the gemm kernel will stay responsible for checking for EXT_ABI (for the transpose).

2022-01-23 18:46 UTC, alheinecke requested changes
I checked out the PR and tested it. Please fix the following 3 merge blockers:
- and incl. for the meltw functions such that they are defined (GCC and clang won't even compile the code right now)
- please add support for FP64 transpose (otherwise "make test" fails)
- @egeor calling setting up the meltw stack-frame inside the GEMM kernel looks weird to me.

After these changes on x86 it should work. For aarch64 "make test" will still fail, but the entire target branch of this PR is not working well on aarch64...

2022-01-23 18:46 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
>    libxsmm_x86_instruction_close_stream_gemm( io_generated_code, &l_gp_reg_mapping, 0, i_xgemm_desc->prefetch );
Please add to the incl. all files that are need for function defintions:
libxsmm_generator_mateltwise_init_micro_kernel_config_fullvector
libxsmm_generator_meltw_setup_stack_frame
libxsmm_generator_transform_norm_to_normt_32bit_avx512_microkernel
libxsmm_generator_meltw_destroy_stack_frame

2022-01-23 18:46 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_meltw_setup_stack_frame( io_generated_code, l_mateltwise_desc, &l_mateltwise_gp_reg_mapping, &l_mateltwise_kernel_config);
We are setting up the GEMM stack and here also the meltw stack 
@egeor does this work in general or does it just work here as transpose is not using any stack variables...?

2022-01-23 18:46 UTC, alheinecke commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_meltw_destroy_stack_frame( io_generated_code, l_mateltwise_desc, &l_mateltwise_kernel_config );
see above the comment on creating the meltw stack

2022-01-23 19:39 UTC, egeor commented on src/generator_gemm_sse_avx_avx2_avx512.c
> +    libxsmm_generator_meltw_setup_stack_frame( io_generated_code, l_mateltwise_desc, &l_mateltwise_gp_reg_mapping, &l_mateltwise_kernel_config);
It does work in general... To put it differently, nested stack frames setup/destroy should work (and already tested in the mateq framework with the various fusions). That said, here nothing happens since no stack vars are used. I saw it already in the PR but didn't comment since to my eyes this is the right way to do it: if tomorrow for whatever reason we decide e.g. for performance to change the leveraged meltw TPP and make it use stack vars, then we don't have to change the GEMM code gen, or for that matter any other code gens that use the leveraged melts TPP. The setup/destroy stack frame will take care of the changes transparently.

2022-01-23 19:41 UTC, egeor commented
> I checked out the PR and tested it. Please fix the following 3 merge blockers:
> 
> * and incl. for the meltw functions such that they are defined (GCC and clang won't even compile the code right now)
> * please add support for FP64 transpose (otherwise "make test" fails)
> * @egeor calling setting up the meltw stack-frame inside the GEMM kernel looks weird to me.
> 
> After these changes on x86 it should work. For aarch64 "make test" will still fail, but the entire target branch of this PR is not working well on aarch64...



> I checked out the PR and tested it. Please fix the following 3 merge blockers:
> 
> * and incl. for the meltw functions such that they are defined (GCC and clang won't even compile the code right now)
> * please add support for FP64 transpose (otherwise "make test" fails)
> * @egeor calling setting up the meltw stack-frame inside the GEMM kernel looks weird to me.
> 
> After these changes on x86 it should work. For aarch64 "make test" will still fail, but the entire target branch of this PR is not working well on aarch64...

See my comment below regarding nested stack frames.

2022-01-24 16:57 UTC, closed without merging